name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
    uses: davecramer/reusableworkflow/.github/workflows/reusable.yml@main
    with:
      config-path: ./manifest.json

  job2:
    runs-on: windows-latest
    needs: job1
    env:
      LIBICONV_VERSION: ${{needs.job1.outputs.LIBICONV_VERSION}}
    steps:
    - shell: powershell
      run: |
       $version = ${{needs.job1.outputs.LIBICONV_VERSION}}
       write-host "version=$version"
  job3:
    runs-on: ubuntu-latest
    needs: job1
    env:
      LIBICONV_VERSION: ${{needs.job1.outputs.LIBICONV_VERSION}}
    steps:
      - run: echo $env.LIBICONV_VERSION