name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
    uses: davecramer/reusableworkflow/.github/workflows/reusable.yml@main
    with:
      config-path: ./manifest.json

  job2:
    runs-on: windows-latest
    needs: job1
    env:
      LIBICONV_VERSION: ${{needs.job1.outputs.LIBICONV_VERSION}}
    steps:
    - shell: powershell
      run: |
       $version = ${{needs.job1.outputs.LIBICONV_VERSION}}
       write-host "version=$version"
  job3:
    runs-on: windows-latest
    needs: job1
    env:
      LIBICONV_VERSION: ${{needs.job1.outputs.LIBICONV_VERSION}}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: mingw-w64-ucrt-x86_64-gcc automake autoconf pkg-config make zip patch tar
    
      - name: Download
        run: |
          curl https://ftp.gnu.org/pub/gnu/libiconv/libiconv-${{ env.LIBICONV_VERSION }}.tar.gz -o ./libiconv-${{ env.LIBICONV_VERSION }}.tar.gz