name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
    uses: davecramer/reusableworkflow/.github/workflows/reusable.yml@main
    with:
      config-path: ./manifest.json

  job2:
    runs-on: windows-latest
    needs: job1
    steps:
    - shell: powershell
      run: |
       $version = ${{needs.job1.outputs.LIBICONV_VERSION}}
       $version