name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
    uses: davecramer/reusableworkflow/.github/workflows/reusable.yml@main
    with:
      config-path: ./manifest.json

  job2:
    runs-on: windows-latest
    needs: job1
    steps:
    - shell: powershell
      run: |
       $version = ${{needs.job1.outputs.LIBICONV_VERSION}}
       write "LIBICONV_VERSION=${{version}}" >> $env:GITHUB_ENV
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - run: echo $env.LIBICONV_VERSION