name: Reusable workflow

on:
  workflow_call:
    inputs:
      config-path:        
        required: true
        default: ./manifest.json
        type: string
    # Map the workflow outputs to job outputs
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.example_job.outputs.output2 }}
      json:
        description: "JSON data"
        value: ${{ jobs.example_job.outputs.output3}}  

jobs:
  example_job:
    name: Generate output
    runs-on: windows-latest
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
      output3: ${{ steps.step3.outputs.json }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2    
      - name: step1
        shell: powershell
        id: step1
        run: write "firstword=hello" >> $env:GITHUB_OUTPUT
      - name: step2
        shell: powershell  
        id: step2
        run: write "secondword=world" >> $env:GITHUB_OUTPUT
      - name: step3
        shell: powershell  
        id: step3
        run: |
          $json = (Get-Content ${{inputs.config-path}} -Raw) | ConvertFrom-Json | ConvertTo-Json -Compress
          write "json=$json" >> $env:GITHUB_OUTPUT